language: node_js
node_js:
  - "node"
before_script:
  - echo $TRAVIS_COMMIT
  - echo $AWS_ACCESS_KEY
  - echo $AWS_SECRET_KEY
script:
  - yarn test
  - yarn build
deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: laur-site
  skip_cleanup: true
  local_dir: build
  cache_control: "max-age=21600"
