language: node_js
node_js:
  - "node"
before_script:
  - echo $TRAVIS_COMMIT
  - echo $AWS_ACCESS_KEY
  - echo $AWS_SECRET_KEY
script:
  - yarn test
  - yarn build
# deploy:
#   provider: s3
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
#   bucket: "laur-site"